#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    autocomplete_method = "coc"
    complete_method = "coc"
    filetree_direction = "left"
    filemanager = "nerdtree"
    project_rooter_automatically = 0
    # options for layers checkers
    enable_neomake = false
    enable_ale = false
    lint_on_the_fly = false

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name = "lang#c"

[[layers]]
enable = false
name = "lang#python"

[[layers]]
name = "lang#html"
enable = true

[[layers]]
enable = true
name = "lang#purescript"

[[layers]]
name = "lang#ruby"

[[layers]]
  name = "lsp"
  enable = true
  filetypes = [
      "c",
      "cpp",
      "python",
#"javascript",
#"purescript"
  ]

[layers.override_cmd]
  python = ["pyls"]
  c = ["clangd"]
  cpp = ["clangd"]
#purescript = ['purescript-language-server', '--stdio']
#javascript = ["javascript-typescript-langserver", "--stdio"]
    #c = ["ccls"]
    #cpp = ["ccls"]

[[layers]]
  name = "checkers"
  enable = false
  #show_cursor_error = true

[[layers]]
  name = "format"

[[layers]]
  name = "core#statusline"
  enable_sidebar = true

[[layers]]
  name = "fzf"

[[layers]]
  name = "ui"
  enable = true

[[custom_plugins]]
name = 'mbbill/fencview'
merged = 0
